🍕 Feature: Footer
Lukyord/bitecare-website pull request #3
Opened 2023-12-14 17:33 UTC by nontharatbang

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description

- Adds Footer and WaveAnimation components
- Additional features to the useInfiniteTranslateX hook and SecondaryButton component
- SVG pictures including 2 waves and 4 social media icons

## Solution
 
- Adding components and adjusting the useInfiniteTranslateX hook/SecondaryButton component according to the design in Figma
- The waves are SVG pictures

## Side Effects

- There are no particular side effects from this PR.

## Related Tickets & Documents

- FIgma: https://www.figma.com/file/HPHxhObRpxtXo4mQiXH2G8/Wireframe---BiteCare?type=design&node-id=283%3A6503&mode=design&t=b2YLPfDDrMlzYyGw-1

## Mobile & Desktop Screenshots/Recordings

- Mobile
<img width="375" alt="Screenshot 2566-12-15 at 00 29 54" src="https://github.com/Lukyord/bitecare-website/assets/73401553/b8ba61e0-05a7-4395-a9a2-514a212e346d">

- Desktop
<img width="1440" alt="Screenshot 2566-12-15 at 00 30 42" src="https://github.com/Lukyord/bitecare-website/assets/73401553/471ea41c-614e-4a89-96cb-13b32b4102bd">
<img width="1437" alt="Screenshot 2566-12-15 at 00 31 29" src="https://github.com/Lukyord/bitecare-website/assets/73401553/bf635f8a-f5ef-47bb-82a5-0605f4e18cb6">

2023-12-15 08:01 UTC, Lukyord requested changes
![image](https://github.com/Lukyord/bitecare-website/assets/98599164/d651278a-6d83-4c6e-bb4c-aca48cdfca11)

have this bug on my machine, not sure what went wrong

2023-12-15 08:01 UTC, Lukyord commented on public/assets/common/shopee-icon.svg
remove unused file

2023-12-15 08:01 UTC, Lukyord commented on public/locales/en/common.json
> +    "get-to-know-us": "Get to Know Us",
move this to `button` translation object

2023-12-15 08:01 UTC, Lukyord commented on public/locales/en/common.json
> +    "online-platform": "Online Platforms"
These translations are the same in Navbar, refactor navbar translations into useNavigation hook and usethem in both Navbar & Footer to maintain only one source of truth and not repeating ourselves. Make sure the hook can be used successfully for both the Navbar and Footer

2023-12-15 08:01 UTC, Lukyord commented on public/locales/th/common.json
> +    "online-platform": "แพลตฟอร์มออนไลน์"
don't forget to update the thai version when refactored

2023-12-15 08:01 UTC, Lukyord commented on src/components/common/Footer/Footer.tsx
> +  const shopeeHref = "https://shopee.co.th/bitecare"
move link into constant folder

2023-12-15 08:01 UTC, Lukyord commented on src/components/common/Footer/Footer.tsx
> +            </div>
change this into separate component for readability and use map() to map icons instead of hard coding everything (in the future social platforms may increase)

2023-12-15 08:01 UTC, Lukyord commented on src/components/common/Footer/Footer.tsx
> +          </div>
Add comment to this section or refactored into different file for readability. Comment each section of your code that is long to improve readability

2023-12-15 08:01 UTC, Lukyord commented on src/components/common/Footer/FooterNavigateSection.tsx
> +  ]
these should comes from useNavigation hook that you need to create after this

2023-12-15 08:01 UTC, Lukyord commented on src/constant/Images.ts
> +import ShopeeIcon from "@public/assets/common/shopee-icon.svg"
remove

2023-12-15 08:01 UTC, Lukyord commented on src/constant/Images.ts
> +  ShopeeIcon,
remove

2023-12-15 08:01 UTC, Lukyord commented on src/hooks/useInfiniteTranslateX.tsx
> +      console.log("in condition")
remove console.log(), all console.log should only be used when debugging

2023-12-15 08:01 UTC, Lukyord commented on src/constant/Images.ts
> +import WaveFooter_2 from "@public/assets/common/wave-footer-2.svg"
add color to both the import names and file names to maintain best practice and consistency in the project

following the conventions in the top of the file, 

ex:
import FlowerBcPrimary_1 from "@public/assets/illustrations/flower-bc-primary-1.svg"
import DogPawBcInversePrimary from "@public/assets/illustrations/dog-paw-bc-inverse-primary.svg"

2023-12-23 15:03 UTC, Lukyord commented
change footer navigation color on hover

2023-12-29 15:10 UTC, nontharatbang commented on src/constant/Images.ts
> +import ShopeeIcon from "@public/assets/common/shopee-icon.svg"
The removed one will be instagram since there's shopee link but not the instagram link

2023-12-29 15:10 UTC, nontharatbang commented on src/constant/Images.ts
> +import ShopeeIcon from "@public/assets/common/shopee-icon.svg"
There're shopee, line, facebook

2024-01-06 02:15 UTC, Lukyord approved these changes
Seems good to me

2024-01-06 02:15 UTC, merged